# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.100-preview2-014569'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*Server*/*.csproj'
    zipAfterPublish: true
    modifyOutputPath: false
    arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) --self-contained --runtime linux-x64

- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifacts
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)
    ArtifactName: drop
